# @author Garrett Rhoads
# @file resolve_singularity.py
# @date 05/21/26
# @brief Discrete geometry - brute force backtracking algo to resolve singularity

import PyNormaliz
from PyNormaliz import *
import numpy as np
import matplotlib.pyplot as plt
from typing import Tuple, List
from sympy import Matrix
from itertools import product
from functools import reduce, lru_cache
from math import gcd
import time

def lattice_in_parallelepiped(vecs):
    n = len(vecs)
    M = Matrix(vecs).T
    determinate = int(M.det())
    sign = 1 if determinate > 0 else -1

    adj = M.adjugate()

    corner = [0] * n
    for v in vecs:
        for j in range(n):
            corner[j] += v[j]

    ranges = []
    for j in range(n):
        ranges.append(range(0, corner[j]))  # include 0, exclude far corner

    candidates = list(product(*ranges))

    result = []
    for pt in candidates:
        if all(c == 0 for c in pt):  # skip origin
            continue
        v = sign * adj * Matrix(pt)
        inside = True
        for i in range(n):
            if not (0 <= int(v[i]) < abs(determinate)):  # half-open: excludes ti=1
                inside = False
                break
        if inside:
            result.append(pt)

    return result

def split(vectors, p):
    sub_cones = []
    for i in range(len(vectors)):
        sub_cone = tuple(p if j == i else vectors[j] for j in range(len(vectors)))
        if int(Matrix(sub_cone).T.det()) != 0:
            sub_cones.append(sub_cone)
    return sub_cones

def is_primitive(pt):
    g = reduce(gcd, pt)
    return g == 1

def is_unimodular(vectors):
    return abs(int(Matrix(vectors).det())) == 1

# i pressed the dynamic programming button and im scared
@lru_cache(maxsize=None)
def decompose(vectors, depth=0):
    indent = "  " * depth
    det = abs(int(Matrix(vectors).det()))

    if is_unimodular(vectors):
        return ()

    candidates = []
    for pt in lattice_in_parallelepiped(vectors):
        if is_primitive(pt):
            candidates.append(pt)

    if not candidates:
        return ()

    best_splits = None
    for idx, p in enumerate(candidates):
        sub_cones = split(vectors, p)
        splits = (p,)
        for sub_cone in sub_cones:
            splits += decompose(sub_cone, depth + 1)
        if best_splits is None or len(splits) < len(best_splits):
            best_splits = splits

    return best_splits

@lru_cache(maxsize=None)
def decompose_bnr(vectors):
    if is_unimodular(vectors):
        return ()

    candidates = []
    for pt in lattice_in_parallelepiped(vectors):
        if is_primitive(pt):
            candidates.append(pt)

    if not candidates:
        raise ValueError(f"non-unimodular cone with no candidates: {vectors}")

    candidates.sort(key=lambda p: sum(x * x for x in p))

    best_result = None
    for p in candidates:
        sub_cones = split(vectors, p)

        # (vectors, p) is the split at this level; sub-cone splits follow recursively
        result = ((vectors, p),)
        for sub_cone in sub_cones:
            result += decompose_bnr(sub_cone)
            if best_result is not None and len(result) >= len(best_result):
                break

        if best_result is None or len(result) < len(best_result):
            best_result = result

    return best_result

def main():
    vectors = tuple(tuple(v) for v in [[1,0,0],[1,3,0],[3,1,4]])
    original_generators = set(vectors)

    print("Input cone generators:")
    for v in vectors:
        print(f"  {list(v)}")

    M = Matrix(vectors).T
    det = int(M.det())
    print(f"\ndet(M) = {det}")
    print(f"lattice points in parallelepiped = {lattice_in_parallelepiped(vectors)}")
    print(f"n = {len(lattice_in_parallelepiped(vectors))}")

    start = time.perf_counter()
    split_sequence = decompose_bnr(vectors)
    elapsed = time.perf_counter() - start

    print(f"\nSplit sequence ({len(split_sequence)} step(s))  [{elapsed:.4f}s]:")
    for i, (cone, split_pt) in enumerate(split_sequence):
        print(f"  Step {i+1}: split {[list(v) for v in cone]}  with  {list(split_pt)}")

    # Replay the split sequence against a running active set to derive
    # the final unimodular cones.  DFS order guarantees each cone being
    # split is already present in active when its step is reached.
    active = {vectors}
    for cone, split_pt in split_sequence:
        active.discard(cone)
        for sub_cone in split(cone, split_pt):
            active.add(sub_cone)

    # The following chunk of code was generated by claude sonnet 4.6
    ##################################################################################################
    unimodular_cones = sorted(active)                                                                #
    print(f"\nResulting unimodular cones ({len(unimodular_cones)}):")                                #
    for i, cone in enumerate(unimodular_cones):                                                      #
        split_pts = [v for v in cone if v not in original_generators]                                #
        label = f"  [split point(s): {[list(sp) for sp in split_pts]}]" if split_pts else ""         #
        print(f"  Cone {i+1}: {[list(v) for v in cone]}{label}")                                     #
    ##################################################################################################
main()